# Generated by Django 5.0.6 on 2024-07-26 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_online_user_last_activity_delete_userstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
