# Generated by Django 5.0.6 on 2024-07-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Отчество'),
        ),
    ]
