# Generated by Django 5.0.6 on 2024-07-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_in_chat',
            field=models.BooleanField(default=False),
        ),
    ]
