# Generated by Django 5.0.6 on 2024-07-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swipe',
            name='target_user',
        ),
        migrations.RemoveField(
            model_name='swipe',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='looking_for',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='search_night_partner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='interests',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='NightPartnerSearch',
        ),
        migrations.DeleteModel(
            name='Swipe',
        ),
    ]
