# Generated by Django 5.0.6 on 2024-07-25 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraction',
            options={'verbose_name': 'Действия пользователя', 'verbose_name_plural': 'Действия пользователей'},
        ),
    ]
