# Generated by Django 5.0.6 on 2024-07-26 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_interest_alter_userprofile_gender_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interest',
            options={'verbose_name': 'Интерес', 'verbose_name_plural': 'Интересы'},
        ),
        migrations.AlterUniqueTogether(
            name='interest',
            unique_together={('name',)},
        ),
    ]
