# Generated by Django 5.0.6 on 2024-07-26 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_interest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='interests',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interests',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Интерес', to='main.interest'),
            preserve_default=False,
        ),
    ]
