# Generated by Django 5.0.6 on 2024-07-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_userprofile_interests_userprofile_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='interests',
            field=models.ManyToManyField(related_name='user_profiles', to='main.interest'),
        ),
    ]
