# Generated by Django 5.0.6 on 2024-09-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_userprofile_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='looking_for',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
