# Generated by Django 5.0.6 on 2024-11-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_userprofile_from_age_userprofile_to_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='from_age',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='to_age',
            field=models.IntegerField(blank=True, max_length=15, null=True),
        ),
    ]
